import Foundation
import SwiftData

enum ExerciseCatalog {
    /// Default logging type for catalog rows is ``ExerciseLoggingType/strength``.
    private static func row(
        _ name: String,
        _ category: String,
        _ aliases: [String],
        _ loggingType: ExerciseLoggingType = .strength
    ) -> (name: String, category: String, aliases: [String], loggingType: ExerciseLoggingType) {
        (name, category, aliases, loggingType)
    }

    // Keep this list hand-editable. `category` is treated as muscle group.
    static let items: [(name: String, category: String, aliases: [String], loggingType: ExerciseLoggingType)] = [
        // Chest
        row("Barbell Bench Press", "Chest", ["bench press", "flat bench", "bench", "chest press", "barbell", "chest"]),
        row("Dumbbell Bench Press", "Chest", ["db bench", "flat dumbbell press", "dumbbell press", "chest press", "pecs"]),
        row("Smith Machine Bench Press", "Chest", ["smith bench", "bench", "chest press"]),
        row("Machine Chest Press", "Chest", ["chest press machine", "machine press", "pecs", "chest"]),
        row("Hammer Strength Chest Press", "Chest", ["plate loaded chest press"]),
        row("Incline Barbell Bench Press", "Chest", ["incline bench"]),
        row("Incline Dumbbell Press", "Chest", ["incline db press"]),
        row("Incline Smith Machine Press", "Chest", ["incline smith bench"]),
        row("Incline Machine Press", "Chest", ["incline chest machine"]),
        row("Decline Barbell Bench Press", "Chest", ["decline bench"]),
        row("Decline Dumbbell Press", "Chest", ["decline db press"]),
        row("Decline Smith Machine Press", "Chest", ["decline smith bench"]),
        row("Machine Decline Press", "Chest", ["decline chest machine"]),
        row("Dumbbell Fly", "Chest", ["flat db fly"]),
        row("Incline Dumbbell Fly", "Chest", ["incline fly"]),
        row("Decline Dumbbell Fly", "Chest", ["decline fly"]),
        row("Cable Fly", "Chest", ["cable crossover"]),
        row("High-to-Low Cable Fly", "Chest", ["high low cable fly"]),
        row("Low-to-High Cable Fly", "Chest", ["low high cable fly"]),
        row("Incline Cable Fly", "Chest", ["incline cable crossover", "low cable fly", "upper chest cable fly"]),
        row("Single-Arm Cable Fly", "Chest", ["one arm cable fly"]),
        row("Pec Deck Fly", "Chest", ["machine fly", "pec deck"]),
        row("Cable Crossover", "Chest", ["standing crossover"]),
        row("Push-Up", "Chest", ["push up", "pushup", "push-up"], .bodyweight),
        row("Wide Push-Up", "Chest", ["wide grip push up", "pushup"], .bodyweight),
        row("Diamond Push-Up", "Chest", ["close grip push up", "pushup"], .bodyweight),
        row("Decline Push-Up", "Chest", ["feet elevated push up", "pushup"], .bodyweight),
        row("Incline Push-Up", "Chest", ["hands elevated push up", "pushup"], .bodyweight),
        row("Weighted Push-Up", "Chest", ["loaded push up"]),
        row("Ring Push-Up", "Chest", ["gymnastic ring push up"], .bodyweight),
        row("Archer Push-Up", "Chest", ["single arm assisted push up"], .bodyweight),
        row("Chest Dip", "Chest", ["forward lean dip", "dip", "dips"], .bodyweight),
        row("Weighted Dip", "Chest", ["weighted chest dip", "weighted triceps dip", "loaded dip", "dip", "dips", "triceps"]),
        row("Landmine Chest Press", "Chest", ["landmine press", "half kneeling landmine press"]),
        row("Single-Arm Landmine Chest Press", "Chest", ["one arm landmine press"]),
        row("Floor Press", "Chest", ["barbell floor press"]),
        row("Dumbbell Floor Press", "Chest", ["db floor press"]),
        row("Svend Press", "Chest", ["plate squeeze press"]),
        row("Guillotine Press", "Chest", ["neck bench press"]),
        row("Pin Press", "Chest", ["bench pin press"]),
        row("Spoto Press", "Chest", ["paused bench press"]),
        row("Board Press", "Chest", ["bench board press"]),
        row("Reverse-Grip Bench Press", "Chest", ["underhand bench press"]),
        row("Machine Fly", "Chest", ["seated fly machine"]),
        row("Standing Cable Press", "Chest", ["cable chest press"]),
        row("Resistance Band Chest Press", "Chest", ["band chest press"]),
        row("Kettlebell Floor Press", "Chest", ["kb floor press"]),
        row("Around the World", "Chest", ["dumbbell around the world"]),
        row("Pullover", "Chest", ["dumbbell pullover"]),
        row("Barbell Pullover", "Chest", ["straight arm pullover"]),
        row("Cable Pullover", "Chest", ["straight arm cable pullover"]),
        row("Squeeze Press", "Chest", ["dumbbell squeeze press"]),
        row("Iso-Lateral Chest Press", "Chest", ["hammer chest press"]),
        row("Plate-Loaded Chest Press", "Chest", ["converging chest press"]),
        row("Neutral-Grip Dumbbell Press", "Chest", ["hammer grip db press"]),
        row("Machine Incline Fly", "Chest", ["incline pec deck"]),
        row("Cross-Body Cable Press", "Chest", ["single arm cable press"]),
        row("Paused Dumbbell Bench Press", "Chest", ["paused db bench"]),
        row("Tempo Bench Press", "Chest", ["slow bench press"]),
        row("Feet-Up Bench Press", "Chest", ["feet on bench bench press"]),
        row("Larsen Press", "Chest", ["legs up bench press"]),

        // Back
        row("Pull-Up", "Back", ["pull up", "pullup", "pull-up", "bodyweight", "lats"], .bodyweight),
        row("Chin-Up", "Back", ["chin up", "chinup", "chin-up", "bodyweight", "lats"], .bodyweight),
        row("Neutral-Grip Pull-Up", "Back", ["parallel pull up"], .bodyweight),
        row("Wide-Grip Pull-Up", "Back", ["wide pull up"], .bodyweight),
        row("Weighted Pull-Up", "Back", ["loaded pull up"]),
        row("Assisted Pull-Up", "Back", ["band assisted pull up"], .bodyweight),
        row("Lat Pulldown", "Back", ["lat pull down", "pulldown", "pull-down", "pull down", "lats", "cable", "back"]),
        row("Wide-Grip Lat Pulldown", "Back", ["wide pulldown", "wide grip pull-down", "pull-down", "pull down", "pulldown", "lats", "back"]),
        row("Close-Grip Lat Pulldown", "Back", ["close pulldown", "close grip pull-down", "pull-down", "pull down", "pulldown", "lats", "back"]),
        row("Neutral-Grip Lat Pulldown", "Back", ["v-bar pulldown", "neutral pull-down", "pull-down", "pull down", "pulldown", "lats", "back"]),
        row("Reverse-Grip Lat Pulldown", "Back", ["underhand lat pulldown", "reverse pull-down", "pull-down", "pull down", "pulldown", "lats", "back"]),
        row("Single-Arm Lat Pulldown", "Back", ["one arm pulldown", "single arm pull-down", "pull-down", "pull down", "pulldown", "lats", "back"]),
        row("Straight-Arm Pulldown", "Back", ["lat prayer", "cable lat prayer", "straight arm pull-down", "pulldown", "pull-down", "lats", "back"]),
        row("Behind-the-Neck Lat Pulldown", "Back", ["behind neck pulldown"]),
        row("Seated Cable Row", "Back", ["cable row", "seated row", "row", "back", "lats"]),
        row("Wide-Grip Seated Row", "Back", ["wide cable row", "cable row", "row"]),
        row("Close-Grip Seated Row", "Back", ["close cable row", "cable row", "row"]),
        row("Single-Arm Cable Row", "Back", ["one arm cable row"]),
        row("Chest-Supported Row", "Back", ["incline bench row"]),
        row("Barbell Row", "Back", ["bent over row", "bb row", "row", "back", "lats"]),
        row("Underhand Barbell Row", "Back", ["reverse grip row"]),
        row("Pendlay Row", "Back", ["dead stop row"]),
        row("Yates Row", "Back", ["semi upright row"]),
        row("T-Bar Row", "Back", ["landmine row"]),
        row("Machine Row", "Back", ["plate loaded row", "machine row", "row", "back"]),
        row("Single-Arm Dumbbell Row", "Back", ["one arm row", "db row", "dumbbell row", "row", "back", "lats"]),
        row("Kroc Row", "Back", ["heavy db row"]),
        row("Meadows Row", "Back", ["landmine single arm row"]),
        row("Chest-Supported Dumbbell Row", "Back", ["incline db row"]),
        row("Chest-Supported Machine Row", "Back", ["machine supported row"]),
        row("Inverted Row", "Back", ["bodyweight row"], .bodyweight),
        row("Ring Row", "Back", ["suspension row"], .bodyweight),
        row("Deadlift", "Back", ["conventional deadlift", "dead lift"]),
        row("Sumo Deadlift", "Back", ["wide stance deadlift"]),
        row("Trap Bar Deadlift", "Back", ["hex bar deadlift"]),
        row("Deficit Deadlift", "Back", ["elevated pull deadlift"]),
        row("Block Pull", "Back", ["rack pull from blocks"]),
        row("Rack Pull", "Back", ["partial deadlift"]),
        row("Snatch-Grip Deadlift", "Back", ["snatch grip deadlift", "wide grip deadlift"]),
        row("Stiff-Leg Deadlift", "Back", ["straight leg deadlift"]),
        row("Good Morning", "Back", ["barbell good morning"]),
        row("Back Extension", "Back", ["hyperextension", "roman chair back extension"]),
        row("45-Degree Back Extension", "Back", ["glute ham raise setup extension"]),
        row("Reverse Hyperextension", "Back", ["reverse hyper", "reverse hyper machine"]),
        row("Shrug", "Back", ["barbell shrug"]),
        row("Dumbbell Shrug", "Back", ["db shrug"]),
        row("Trap Bar Shrug", "Back", ["hex bar shrug"]),
        row("Machine Shrug", "Back", ["shrug machine"]),
        row("Farmer Shrug", "Back", ["farmer hold shrug"]),
        row("Seal Row", "Back", ["chest supported barbell row"]),
        row("Helms Row", "Back", ["chest supported landmine row"]),
        row("Renegade Row", "Back", ["plank db row"]),
        row("Cable High Row", "Back", ["high cable row"]),
        row("Machine High Row", "Back", ["hammer high row"]),
        row("Iso-Lateral Row", "Back", ["hammer row"]),
        row("Landmine Row", "Back", ["two hand landmine row"]),
        row("Kettlebell Row", "Back", ["kb bent over row"]),
        row("Resistance Band Row", "Back", ["band row"]),
        row("Jefferson Deadlift", "Back", ["jefferson lift"]),
        row("Deficit Barbell Row", "Back", ["elevated row"]),
        row("Paused Barbell Row", "Back", ["paused bent over row"]),
        row("Gorilla Row", "Back", ["kettlebell gorilla row"]),
        row("Machine Pullover", "Back", ["nautilus pullover", "lat pullover machine", "pullover machine"]),
        row("Rope Climb", "Back", ["climbing rope"], .bodyweight),
        row("Muscle-Up", "Back", ["bar muscle up"], .bodyweight),
        row("Scapular Pull-Up", "Back", ["scap pull up"], .bodyweight),
        row("Scapular Push-Up", "Back", ["scap push up"], .bodyweight),
        row("Hammer Strength Pulldown", "Back", ["plate pulldown"]),
        row("Hammer Strength Row", "Back", ["plate row"]),
        row("Smith Machine Row", "Back", ["smith bent over row"]),
        row("Smith Machine Shrug", "Back", ["smith shrug"]),
        row("Cable Shrug", "Back", ["low cable shrug"]),
        row("Power Shrug", "Back", ["explosive shrug"]),

        // Shoulders
        row("Barbell Overhead Press", "Shoulders", ["ohp", "military press", "overhead press", "shoulder press", "press", "barbell", "shoulders"]),
        row("Seated Barbell Overhead Press", "Shoulders", ["seated ohp", "seated overhead press", "barbell shoulder press"]),
        row("Push Press", "Shoulders", ["barbell push press"]),
        row("Behind-the-Neck Press", "Shoulders", ["btnp"]),
        row("Dumbbell Shoulder Press", "Shoulders", ["db ohp", "dumbbell overhead press", "shoulder press", "dumbbell press", "shoulders"]),
        row("Seated Dumbbell Shoulder Press", "Shoulders", ["seated db press", "seated dumbbell press", "dumbbell overhead press", "shoulder press"]),
        row("Standing Dumbbell Shoulder Press", "Shoulders", ["standing db press", "standing dumbbell press", "dumbbell overhead press", "shoulder press"]),
        row("Arnold Press", "Shoulders", ["arnold dumbbell press"]),
        row("Machine Shoulder Press", "Shoulders", ["shoulder press machine", "machine overhead press", "machine press", "shoulders"]),
        row("Plate-Loaded Shoulder Press", "Shoulders", ["hammer strength shoulder press", "iso-lateral shoulder press", "machine shoulder press", "plate loaded press"]),
        row("Smith Machine Overhead Press", "Shoulders", ["smith ohp", "smith machine shoulder press", "smith shoulder press", "overhead press"]),
        row("Landmine Shoulder Press", "Shoulders", ["standing landmine press"]),
        row("Single-Arm Landmine Shoulder Press", "Shoulders", ["one arm landmine shoulder press"]),
        row("Kettlebell Press", "Shoulders", ["kb overhead press"]),
        row("Bottoms-Up Kettlebell Press", "Shoulders", ["kb bottoms up press"]),
        row("Z Press", "Shoulders", ["seated floor press shoulders"]),
        row("Viking Press", "Shoulders", ["landmine viking press"]),
        row("Bradford Press", "Shoulders", ["front to back press"]),
        row("Cuban Press", "Shoulders", ["external rotation press"]),
        row("Dumbbell Lateral Raise", "Shoulders", ["side raise", "lateral raise", "delt", "delts", "shoulders"]),
        row("Cable Lateral Raise", "Shoulders", ["cable side raise", "side delt cable raise"]),
        row("Machine Lateral Raise", "Shoulders", ["lateral raise machine", "side delt machine", "machine side raise"]),
        row("Single-Arm Cable Lateral Raise", "Shoulders", ["one arm cable lateral raise", "single arm cable side raise", "side delt cable raise"]),
        row("Lean-Away Cable Lateral Raise", "Shoulders", ["leaning lateral raise"]),
        row("Seated Lateral Raise", "Shoulders", ["seated side raise"]),
        row("Partial Lateral Raise", "Shoulders", ["heavy partial lateral"]),
        row("Dumbbell Front Raise", "Shoulders", ["front raise"]),
        row("Cable Front Raise", "Shoulders", ["cable front raise"]),
        row("Plate Front Raise", "Shoulders", ["plate raise"]),
        row("Barbell Front Raise", "Shoulders", ["bb front raise"]),
        row("Rear Delt Fly", "Shoulders", ["reverse fly"]),
        row("Reverse Pec Deck", "Shoulders", ["rear delt machine"]),
        row("Bent-Over Rear Delt Raise", "Shoulders", ["bent over rear raise"]),
        row("Cable Rear Delt Fly", "Shoulders", ["cable reverse fly"]),
        row("Face Pull", "Shoulders", ["rope face pull", "rear delt", "rear delts", "rope", "cable", "shoulders"]),
        row("Upright Row", "Shoulders", ["barbell upright row"]),
        row("Dumbbell Upright Row", "Shoulders", ["db upright row"]),
        row("Cable Upright Row", "Shoulders", ["cable upright row"]),
        row("Smith Machine Upright Row", "Shoulders", ["smith upright row"]),
        row("Lu Raise", "Shoulders", ["lu lateral raise complex"]),
        row("Y Raise", "Shoulders", ["prone y raise"]),
        row("T Raise", "Shoulders", ["prone t raise"]),
        row("W Raise", "Shoulders", ["prone w raise"]),
        row("Bus Driver", "Shoulders", ["plate rotation press"]),
        row("Landmine Lateral Raise", "Shoulders", ["landmine side raise"]),
        row("Kettlebell Halo", "Shoulders", ["kb halo"]),
        row("Band Pull-Apart", "Shoulders", ["band pull apart"]),
        row("Scaption Raise", "Shoulders", ["scapular plane raise"]),
        row("Cable Y-Raise", "Shoulders", ["cable y raise"]),
        row("Handstand Push-Up", "Shoulders", ["wall handstand press"], .bodyweight),
        row("Pike Push-Up", "Shoulders", ["pike press"], .bodyweight),
        row("Wall Walk", "Shoulders", ["handstand walk prep"], .bodyweight),
        row("Neck Flexion", "Shoulders", ["neck curl"]),
        row("Neck Extension", "Shoulders", ["neck extension"]),
        row("Neck Lateral Flexion", "Shoulders", ["side neck bend"]),
        row("Plate Neck Harness Extension", "Shoulders", ["neck harness"]),
        row("Cross-Body Cable Lateral Raise", "Shoulders", ["cross cable lateral"]),
        row("Single-Arm Cable Front Raise", "Shoulders", ["one arm front raise"]),
        row("Resistance Band Lateral Raise", "Shoulders", ["band lateral raise"]),
        row("Resistance Band Overhead Press", "Shoulders", ["band ohp"]),
        row("Pin Press Overhead", "Shoulders", ["overhead pin press"]),

        // Biceps
        row("Barbell Curl", "Biceps", ["bb curl", "curl", "barbell", "biceps"]),
        row("EZ-Bar Curl", "Biceps", ["ez curl", "ez bar", "curl", "biceps"]),
        row("Dumbbell Curl", "Biceps", ["db curl", "dumbbell", "curl", "biceps"]),
        row("Alternating Dumbbell Curl", "Biceps", ["alt db curl"]),
        row("Incline Dumbbell Curl", "Biceps", ["incline curl"]),
        row("Seated Dumbbell Curl", "Biceps", ["seated curl"]),
        row("Concentration Curl", "Biceps", ["concentration db curl"]),
        row("Preacher Curl", "Biceps", ["preacher bench curl"]),
        row("Machine Preacher Curl", "Biceps", ["preacher machine"]),
        row("Spider Curl", "Biceps", ["prone incline curl"]),
        row("Cable Curl", "Biceps", ["standing cable curl"]),
        row("High Cable Curl", "Biceps", ["overhead cable curl"]),
        row("Bayesian Cable Curl", "Biceps", ["behind body cable curl"]),
        row("Hammer Curl", "Biceps", ["neutral grip curl", "hammer", "biceps"]),
        row("Cross-Body Hammer Curl", "Biceps", ["cross body curl"]),
        row("Rope Hammer Curl", "Biceps", ["cable hammer curl"]),
        row("Reverse Curl", "Biceps", ["pronated curl"]),
        row("Drag Curl", "Biceps", ["barbell drag curl"]),
        row("Cheat Curl", "Biceps", ["heavy cheat curl"]),
        row("21s Curl", "Biceps", ["barbell 21s"]),
        row("Zottman Curl", "Biceps", ["zottman db curl"]),
        row("Pinwheel Curl", "Biceps", ["offset hammer curl"]),
        row("Machine Curl", "Biceps", ["biceps curl machine"]),
        row("Cable Preacher Curl", "Biceps", ["cable preacher curl"]),
        row("Single-Arm Cable Curl", "Biceps", ["one arm cable curl"]),
        row("Resistance Band Curl", "Biceps", ["band curl"]),
        row("Kettlebell Curl", "Biceps", ["kb curl"]),
        row("Fat-Grip Curl", "Biceps", ["thick bar curl"]),
        row("Wrist Curl", "Biceps", ["barbell wrist curl"]),
        row("Reverse Wrist Curl", "Biceps", ["extension wrist curl"]),
        row("Behind-the-Back Wrist Curl", "Biceps", ["behind back wrist curl"]),
        row("Dumbbell Wrist Curl", "Biceps", ["db wrist curl"]),
        row("Farmer Hold", "Biceps", ["static farmer hold"], .duration),
        row("Plate Pinch Hold", "Biceps", ["pinch grip hold"], .duration),
        row("Towel Pull-Up", "Biceps", ["towel grip pull up"], .bodyweight),
        row("Ring Curl", "Biceps", ["suspension curl"], .bodyweight),
        row("Cable Drag Curl", "Biceps", ["cable drag curl"]),
        row("Lying Cable Curl", "Biceps", ["floor cable curl"]),
        row("Incline Cable Curl", "Biceps", ["incline bench cable curl"]),
        row("Machine Hammer Curl", "Biceps", ["neutral curl machine"]),
        row("Iso-Lateral Curl", "Biceps", ["hammer curl machine"]),
        row("Tempo Barbell Curl", "Biceps", ["slow curl"]),
        row("Paused Barbell Curl", "Biceps", ["paused curl"]),
        row("Cable Rope Curl", "Biceps", ["rope biceps curl"]),
        row("Landmine Curl", "Biceps", ["landmine biceps curl"]),

        // Triceps
        row("Close-Grip Bench Press", "Triceps", ["cg bench", "close grip bench", "tricep bench", "triceps bench"]),
        row("Skull Crusher", "Triceps", ["lying triceps extension", "lying tricep extension", "ez bar", "triceps", "tricep"]),
        row("EZ-Bar Skull Crusher", "Triceps", ["ez skull crusher", "ez bar skullcrusher", "lying triceps extension", "triceps", "tricep"]),
        row("Barbell Overhead Triceps Extension", "Triceps", ["standing bar extension", "overhead tricep extension"]),
        row("Seated Dumbbell Overhead Triceps Extension", "Triceps", ["seated db extension", "dumbbell overhead extension", "overhead tricep extension"]),
        row("Single-Arm Dumbbell Overhead Triceps Extension", "Triceps", ["one arm db extension", "single arm dumbbell tricep extension"]),
        row("Cable Triceps Pushdown", "Triceps", ["cable pushdown", "tricep pushdown", "triceps pressdown", "pushdown", "pressdown", "cable", "triceps", "tricep", "tri"]),
        row("Rope Triceps Pushdown", "Triceps", ["rope pushdown", "rope pressdown", "cable rope pushdown", "pushdown", "pressdown", "rope", "cable", "triceps", "tricep", "tri"]),
        row("Straight Bar Triceps Pushdown", "Triceps", ["straight-bar pushdown", "straight bar pushdown", "bar pushdown", "straight bar pressdown", "pushdown", "pressdown", "cable", "triceps", "tricep", "tri"]),
        row("V-Bar Triceps Pushdown", "Triceps", ["v-bar pushdown", "v bar pushdown", "v bar triceps pushdown", "v-bar pressdown", "pushdown", "pressdown", "cable", "triceps", "tricep", "tri"]),
        row("Reverse Grip Triceps Pushdown", "Triceps", ["reverse-grip pushdown", "underhand pushdown", "reverse grip pressdown", "pushdown", "pressdown", "cable", "triceps", "tricep", "tri"]),
        row("Single-Arm Cable Triceps Pushdown", "Triceps", ["single arm cable pushdown", "one arm pushdown", "one arm cable pushdown", "pushdown", "pressdown", "cable", "triceps", "tricep", "tri"]),
        row("Single-Arm Rope Triceps Pushdown", "Triceps", ["single arm rope pushdown", "one arm rope pushdown", "rope pressdown", "pushdown", "pressdown", "rope", "cable", "triceps", "tricep", "tri"]),
        row("Cable Overhead Triceps Extension", "Triceps", ["overhead cable triceps extension", "cable overhead extension", "cable tricep extension", "triceps extension", "tricep extension"]),
        row("Rope Overhead Triceps Extension", "Triceps", ["rope overhead extension", "overhead rope extension", "rope cable extension", "triceps extension", "tricep extension", "rope", "cable"]),
        row("Dumbbell Skull Crusher", "Triceps", ["db skull crusher", "lying dumbbell triceps extension", "lying db triceps extension", "dumbbell tricep extension"]),
        row("JM Press", "Triceps", ["jm bench press"]),
        row("Bench Dip", "Triceps", ["triceps bench dip", "tricep bench dip", "dip", "dips"], .bodyweight),
        row("Parallel Bar Dip", "Triceps", ["triceps dip", "tricep dip", "bodyweight dip", "dip", "dips"], .bodyweight),
        row("Ring Dip", "Triceps", ["gymnastic dip"], .bodyweight),
        row("Assisted Triceps Dip", "Triceps", ["assisted dip", "assisted dip machine", "machine triceps dip", "dip machine", "tricep dip", "dip", "dips"], .bodyweight),
        row("Kickback", "Triceps", ["dumbbell kickback"]),
        row("Cable Triceps Kickback", "Triceps", ["cable kickback", "tricep kickback", "triceps kickback"]),
        row("Tate Press", "Triceps", ["lying db tate press"]),
        row("California Press", "Triceps", ["hybrid press extension"]),
        row("Floor Press Close-Grip", "Triceps", ["close grip floor press"]),
        row("Board Press Close-Grip", "Triceps", ["close grip board press"]),
        row("Pin Press Close-Grip", "Triceps", ["close grip pin press"]),
        row("Machine Triceps Extension", "Triceps", ["triceps machine", "tricep extension machine", "machine tricep extension"]),
        row("Resistance Band Pushdown", "Triceps", ["band pushdown"]),
        row("Resistance Band Overhead Extension", "Triceps", ["band overhead extension"]),
        row("Bodyweight Triceps Extension", "Triceps", ["bodyweight skull crusher"], .bodyweight),
        row("Suspension Triceps Press", "Triceps", ["trx triceps press"], .bodyweight),
        row("Cross-Body Cable Extension", "Triceps", ["single arm cross extension"]),
        row("Tempo Skull Crusher", "Triceps", ["slow skull crusher"]),
        row("Paused Close-Grip Bench Press", "Triceps", ["paused cg bench"]),
        row("Rolling Dumbbell Extension", "Triceps", ["rolling db extension"]),
        row("Cable Concentration Extension", "Triceps", ["kneeling cable extension"]),
        row("Kettlebell Overhead Extension", "Triceps", ["kb triceps extension"]),
        row("Landmine Triceps Extension", "Triceps", ["landmine extension"]),

        // Legs
        row("Back Squat", "Legs", ["barbell squat", "squat", "back squat", "legs", "quads"]),
        row("Low-Bar Back Squat", "Legs", ["low bar squat", "squat", "back squat"]),
        row("High-Bar Back Squat", "Legs", ["high bar squat", "squat", "back squat"]),
        row("Front Squat", "Legs", ["front rack squat", "front squat", "squat", "legs"]),
        row("Safety Bar Squat", "Legs", ["ssb squat"]),
        row("Zercher Squat", "Legs", ["zercher squat"]),
        row("Box Squat", "Legs", ["box back squat"]),
        row("Pause Squat", "Legs", ["paused squat"]),
        row("Tempo Squat", "Legs", ["slow squat"]),
        row("Anderson Squat", "Legs", ["pin squat from bottom"]),
        row("Overhead Squat", "Legs", ["oh squat"]),
        row("Goblet Squat", "Legs", ["dumbbell goblet squat"]),
        row("Kettlebell Goblet Squat", "Legs", ["kb goblet squat"]),
        row("Hack Squat", "Legs", ["machine hack squat"]),
        row("Pendulum Squat", "Legs", ["pendulum squat machine"]),
        row("V-Squat", "Legs", ["v squat machine"]),
        row("Belt Squat", "Legs", ["belt squat machine"]),
        row("Leg Press", "Legs", ["sled leg press", "leg press", "machine", "quads"]),
        row("Single-Leg Press", "Legs", ["one leg press"]),
        row("Horizontal Leg Press", "Legs", ["seated leg press"]),
        row("Sissy Squat", "Legs", ["sissy squat machine"], .bodyweight),
        row("Spanish Squat", "Legs", ["band spanish squat"]),
        row("Split Squat", "Legs", ["static lunge"]),
        row("Bulgarian Split Squat", "Legs", ["bss", "rear foot elevated split squat", "bulgarian", "split squat", "lunge", "legs"]),
        row("Walking Lunge", "Legs", ["walking lunges"]),
        row("Reverse Lunge", "Legs", ["backward lunge"]),
        row("Forward Lunge", "Legs", ["step forward lunge"]),
        row("Lateral Lunge", "Legs", ["side lunge"]),
        row("Curtsy Lunge", "Legs", ["curtsy squat"]),
        row("Deficit Reverse Lunge", "Legs", ["elevated reverse lunge"]),
        row("Step-Up", "Legs", ["box step up"]),
        row("Deficit Step-Up", "Legs", ["high step up"]),
        row("Romanian Deadlift", "Legs", ["rdl", "romanian", "hinge", "hamstrings", "glutes", "dead lift"]),
        row("Single-Leg Romanian Deadlift", "Legs", ["single leg rdl"]),
        row("Leg Extension", "Legs", ["quad extension", "quads", "machine", "leg extension"]),
        row("Single-Leg Extension", "Legs", ["unilateral leg extension"]),
        row("Lying Leg Curl", "Legs", ["prone leg curl", "hamstring curl", "hamstrings", "machine", "leg curl"]),
        row("Seated Leg Curl", "Legs", ["hamstring curl machine", "leg curl", "hamstrings", "machine"]),
        row("Standing Leg Curl", "Legs", ["standing ham curl"]),
        row("Nordic Curl", "Legs", ["nordic hamstring curl"], .bodyweight),
        row("Glute-Ham Raise", "Legs", ["ghr"]),
        row("Reverse Nordic", "Legs", ["reverse nordic curl"], .bodyweight),
        row("Copenhagen Plank", "Legs", ["adductor plank"], .duration),
        row("Standing Calf Raise", "Legs", ["calf raise", "calves", "calf", "standing", "machine"]),
        row("Seated Calf Raise", "Legs", ["seated calf", "calves", "calf", "seated", "machine"]),
        row("Leg Press Calf Raise", "Legs", ["sled calf raise"]),
        row("Donkey Calf Raise", "Legs", ["donkey calf"]),
        row("Smith Machine Calf Raise", "Legs", ["smith calf raise"]),
        row("Tibialis Raise", "Legs", ["tib bar raise"]),
        row("Seated Tibialis Raise", "Legs", ["tibialis anterior machine"]),
        row("Hip Adduction Machine", "Legs", ["adductor machine"]),
        row("Hip Abduction Machine", "Legs", ["abductor machine"]),
        row("Smith Machine Squat", "Legs", ["smith squat"]),
        row("Smith Machine Lunge", "Legs", ["smith lunge"]),
        row("Landmine Squat", "Legs", ["landmine squat"]),
        row("Landmine Lunge", "Legs", ["landmine lunge"]),
        row("Jefferson Squat", "Legs", ["jefferson squat"]),
        row("Pistol Squat", "Legs", ["single leg squat"], .bodyweight),
        row("Shrimp Squat", "Legs", ["quad dominant pistol"], .bodyweight),
        row("Cossack Squat", "Legs", ["side squat"], .bodyweight),
        row("Wall Sit", "Legs", ["isometric squat hold"], .duration),
        row("Jump Squat", "Legs", ["barbell jump squat"]),
        row("Vertical Jump", "Legs", ["standing vertical jump"], .bodyweight),
        row("Hatfield Squat", "Legs", ["ssb hatfield squat"]),
        row("Kang Squat", "Legs", ["hybrid squat good morning"]),
        row("Trap Bar Carry", "Legs", ["hex bar carry"]),
        row("Banded Squat", "Legs", ["resistance band squat"]),
        row("Banded Leg Curl", "Legs", ["band hamstring curl"]),
        row("Terminal Knee Extension", "Legs", ["tke band"]),
        row("Peterson Step-Up", "Legs", ["knee over toe step up"]),
        row("Poliquin Step-Up", "Legs", ["elevated step up"]),
        row("Heels-Elevated Squat", "Legs", ["quad bias squat"]),
        row("Toes-Elevated Squat", "Legs", ["glute bias squat"]),

        // Glutes
        row("Barbell Hip Thrust", "Glutes", ["hip thrust", "hipthrust", "glutes", "bridge"]),
        row("Dumbbell Hip Thrust", "Glutes", ["db hip thrust", "hip thrust", "glutes"]),
        row("Machine Hip Thrust", "Glutes", ["hip thrust machine"]),
        row("Glute Drive Machine", "Glutes", ["glute drive", "hip thrust machine", "machine hip thrust", "glutes"]),
        row("Banded Hip Thrust", "Glutes", ["resistance band hip thrust"]),
        row("Single-Leg Hip Thrust", "Glutes", ["one leg hip thrust"]),
        row("Glute Bridge", "Glutes", ["barbell glute bridge", "glute bridge", "bridge", "glutes"]),
        row("Single-Leg Glute Bridge", "Glutes", ["one leg bridge"]),
        row("Frog Pump", "Glutes", ["frog bridge"]),
        row("Kas Glute Bridge", "Glutes", ["short range hip thrust"]),
        row("Cable Glute Kickback", "Glutes", ["glute kickback", "cable kickback", "cable glute extension"]),
        row("Machine Glute Kickback", "Glutes", ["kickback machine"]),
        row("Donkey Kick", "Glutes", ["quadruped kickback"], .bodyweight),
        row("Fire Hydrant", "Glutes", ["quadruped hip abduction"], .bodyweight),
        row("Clamshell", "Glutes", ["band clamshell"]),
        row("Seated Hip Abduction Machine", "Glutes", ["hip abduction machine", "abductor machine", "seated abductor machine", "glute abduction", "glutes"]),
        row("Cable Hip Abduction", "Glutes", ["standing cable abduction"]),
        row("Banded Lateral Walk", "Glutes", ["monster walk", "lateral band walk", "side step band", "band side walk"]),
        row("Cable Pull-Through", "Glutes", ["rope pull through"]),
        row("Step-Down", "Glutes", ["eccentric step down"]),
        row("Frog Hip Thrust", "Glutes", ["frog stance thrust"]),
        row("Smith Machine Hip Thrust", "Glutes", ["smith hip thrust"]),
        row("Landmine RDL", "Glutes", ["landmine rdl"]),
        row("Paused Hip Thrust", "Glutes", ["isometric hip thrust"]),
        row("B-stance Hip Thrust", "Glutes", ["staggered hip thrust"]),
        row("Hip Extension Machine", "Glutes", ["glute extension machine"]),
        row("Standing Glute Pushdown", "Glutes", ["cable glute press"]),
        row("Reverse Lunge to Knee Drive", "Glutes", ["lunge knee drive"]),
        row("Cable Step-Up", "Glutes", ["cable resisted step up"]),
        row("Sandbag Bear Hug Squat", "Glutes", ["bear hug squat"]),

        // Core
        row("Plank", "Core", ["front plank", "plank", "hold", "core"], .duration),
        row("Side Plank", "Core", ["lateral plank", "side plank", "plank", "hold", "core"], .duration),
        row("RKC Plank", "Core", ["hardstyle plank"], .duration),
        row("Weighted Plank", "Core", ["loaded plank"], .duration),
        row("Plank Shoulder Tap", "Core", ["shoulder tap plank"], .bodyweight),
        row("Dead Bug", "Core", ["deadbug"], .bodyweight),
        row("Bird Dog", "Core", ["quadruped bird dog"], .bodyweight),
        row("Hollow Body Hold", "Core", ["hollow hold"], .duration),
        row("Arch Hold", "Core", ["superman hold"], .duration),
        row("Crunch", "Core", ["ab crunch", "crunch", "abs", "core", "abdominal"], .bodyweight),
        row("Bicycle Crunch", "Core", ["cross body crunch"], .bodyweight),
        row("Reverse Crunch", "Core", ["hip lift crunch"], .bodyweight),
        row("Sit-Up", "Core", ["ab sit up", "sit up", "situp", "sit-up", "abs", "core"], .bodyweight),
        row("Weighted Sit-Up", "Core", ["loaded sit up"]),
        row("V-Up", "Core", ["jackknife"], .bodyweight),
        row("Toes to Bar", "Core", ["ttb"], .bodyweight),
        row("Hanging Leg Raise", "Core", ["hanging knee raise"], .bodyweight),
        row("Hanging Knee Raise", "Core", ["captain knee raise"], .bodyweight),
        row("Captain Chair Leg Raise", "Core", ["vertical leg raise"], .bodyweight),
        row("Captain Chair Knee Raise", "Core", ["roman chair knee raise"], .bodyweight),
        row("Cable Crunch", "Core", ["kneeling cable crunch"]),
        row("Machine Crunch", "Core", ["ab machine"]),
        row("Decline Sit-Up", "Core", ["decline ab sit up"], .bodyweight),
        row("GHD Sit-Up", "Core", ["glute ham sit up"], .bodyweight),
        row("Pallof Press", "Core", ["anti rotation press"]),
        row("Pallof Hold", "Core", ["anti rotation hold"], .duration),
        row("Landmine Rotation", "Core", ["landmine twist"]),
        row("Russian Twist", "Core", ["weighted russian twist"]),
        row("Medicine Ball Slam", "Core", ["ball slam"]),
        row("Wood Chop", "Core", ["cable woodchop"]),
        row("High-to-Low Wood Chop", "Core", ["diagonal chop down"]),
        row("Low-to-High Wood Chop", "Core", ["diagonal chop up"]),
        row("Ab Wheel Rollout", "Core", ["ab rollout"], .bodyweight),
        row("Barbell Rollout", "Core", ["barbell ab rollout"]),
        row("Stability Ball Rollout", "Core", ["swiss ball rollout"], .bodyweight),
        row("Dragon Flag", "Core", ["dragonflag"], .bodyweight),
        row("L-Sit", "Core", ["l sit hold"], .duration),
        row("Hanging L-Sit", "Core", ["bar l sit"], .duration),
        row("Windmill", "Core", ["kb windmill"]),
        row("Stir the Pot", "Core", ["stability ball plank"], .bodyweight),
        row("Mountain Climber", "Core", ["running plank"], .bodyweight),
        row("Dead Bug with Band", "Core", ["band resisted dead bug"]),
        row("Cable Pallof Press", "Core", ["standing pallof"]),
        row("Side Bend", "Core", ["dumbbell side bend"]),
        row("Saxon Side Bend", "Core", ["plate side bend"]),
        row("Hip Dip Side Plank", "Core", ["side plank dip"], .bodyweight),
        row("Copenhagen Side Plank", "Core", ["copenhagen side"], .duration),
        row("Hollow Rock", "Core", ["hollow body rock"], .bodyweight),
        row("V-Sit", "Core", ["v sit"], .duration),
        row("Jackknife", "Core", ["bench jackknife"], .bodyweight),
        row("Flutter Kick", "Core", ["scissor kick"], .bodyweight),
        row("Leg Raise", "Core", ["lying leg raise", "leg raise", "abs", "core"], .bodyweight),
        row("McGill Curl-Up", "Core", ["curl up"]),
        row("Side Crunch", "Core", ["oblique crunch"], .bodyweight),
        row("Oblique Cable Crunch", "Core", ["kneeling oblique crunch"]),
        row("Landmine Anti-Rotation", "Core", ["landmine pallof"]),
        row("Plank Up-Down", "Core", ["plank to push up"], .bodyweight),
        row("Body Saw", "Core", ["slider plank"], .bodyweight),
        row("TRX Fallout", "Core", ["suspension fallout"], .bodyweight),
        row("Resistance Band Pallof", "Core", ["band pallof"]),

        // Cardio
        row("Treadmill Walk", "Cardio", ["incline walk", "walk", "walking", "treadmill", "cardio"], .cardio),
        row("Treadmill Run", "Cardio", ["indoor run", "run", "running", "treadmill", "cardio"], .cardio),
        row("Treadmill Incline Walk", "Cardio", ["12-3-30 walk", "treadmill walk", "walking"], .cardio),
        row("Outdoor Walk", "Cardio", ["walking", "walk"], .cardio),
        row("Outdoor Run", "Cardio", ["jog", "running", "run"], .cardio),
        row("Outdoor Sprint", "Cardio", ["sprints"], .cardio),
        row("Trail Run", "Cardio", ["trail running"], .cardio),
        row("Stationary Bike", "Cardio", ["exercise bike", "bike", "cycling", "stationary bike", "cardio"], .cardio),
        row("Upright Bike", "Cardio", ["upright cycle", "bike", "cycling"], .cardio),
        row("Recumbent Bike", "Cardio", ["recumbent cycle", "bike", "cycling"], .cardio),
        row("Spin Bike", "Cardio", ["indoor cycling", "bike", "cycling"], .cardio),
        row("Air Bike", "Cardio", ["assault bike", "fan bike"], .cardio),
        row("Elliptical", "Cardio", ["cross trainer", "elliptical trainer", "cardio"], .cardio),
        row("Rowing Machine", "Cardio", ["row erg", "erg row", "rower", "rowing", "erg", "cardio"], .cardio),
        row("Stair Climber", "Cardio", ["stepmill", "stair climber", "cardio"], .cardio),
        row("StairMaster", "Cardio", ["stair master", "stair climber", "cardio"], .cardio),
        row("Ski Erg", "Cardio", ["ski machine", "ski erg", "cardio"], .cardio),
        row("VersaClimber", "Cardio", ["vertical climber"], .cardio),
        row("Jacob's Ladder", "Cardio", ["ladder climber"], .cardio),
        row("Jump Rope", "Cardio", ["skipping"], .cardio),
        row("Double-Under", "Cardio", ["double unders"], .cardio),
        row("Battle Ropes", "Cardio", ["wave ropes"], .cardio),
        row("Swimming", "Cardio", ["pool swim"], .cardio),
        row("Open Water Swim", "Cardio", ["lake swim"], .cardio),
        row("Rowing Erg Intervals", "Cardio", ["erg intervals"], .cardio),
        row("Bike Erg", "Cardio", ["concept2 bike"], .cardio),
        row("High Knees", "Cardio", ["running high knees"], .cardio),
        row("Butt Kicks", "Cardio", ["heel kicks"], .cardio),
        row("Shadow Boxing", "Cardio", ["boxing cardio"], .cardio),
        row("Heavy Bag Work", "Cardio", ["punching bag"], .cardio),
        row("Jumping Jack", "Cardio", ["star jump"], .cardio),
        row("Box Step", "Cardio", ["step aerobics"], .cardio),
        row("Hill Sprint", "Cardio", ["hill repeats"], .cardio),
        row("Tempo Run", "Cardio", ["threshold run"], .cardio),
        row("Interval Run", "Cardio", ["hiit run"], .cardio),
        row("Rucking", "Cardio", ["weighted hike"], .cardio),
        row("Hiking", "Cardio", ["trail hike"], .cardio),
        row("Cross-Country Ski Erg", "Cardio", ["xc ski erg"], .cardio),
        row("Pool Running", "Cardio", ["aqua jog"], .cardio),
        row("Kickboxing", "Cardio", ["cardio kickboxing"], .cardio),
        row("Dance Cardio", "Cardio", ["dance fitness"], .cardio),
        row("Rowing Sprint", "Cardio", ["500m row"], .cardio),
        row("Cycling Intervals", "Cardio", ["bike intervals"], .cardio),

        // Full Body
        row("Burpee", "Full Body", ["sprawl"], .bodyweight),
        row("Burpee Box Jump", "Full Body", ["burpee to box"], .bodyweight),
        row("Thruster", "Full Body", ["squat to press"]),
        row("Dumbbell Thruster", "Full Body", ["db thruster"]),
        row("Kettlebell Thruster", "Full Body", ["kb thruster"]),
        row("Kettlebell Swing", "Full Body", ["kb swing"]),
        row("American Kettlebell Swing", "Full Body", ["overhead kb swing"]),
        row("Russian Kettlebell Swing", "Full Body", ["eye level swing"]),
        row("Man Maker", "Full Body", ["dumbbell man maker"]),
        row("Devil Press", "Full Body", ["double db devil press"]),
        row("Dumbbell Snatch", "Full Body", ["single arm db snatch"]),
        row("Kettlebell Snatch", "Full Body", ["kb snatch"]),
        row("Dumbbell Clean", "Full Body", ["db clean"]),
        row("Kettlebell Clean", "Full Body", ["kb clean"]),
        row("Dumbbell Clean and Press", "Full Body", ["db clean press"]),
        row("Kettlebell Clean and Press", "Full Body", ["kb clean press"]),
        row("Farmer Carry", "Full Body", ["farmers walk"]),
        row("Suitcase Carry", "Full Body", ["single arm farmer"]),
        row("Overhead Carry", "Full Body", ["oh walk"]),
        row("Front Rack Carry", "Full Body", ["front rack walk"]),
        row("Zercher Carry", "Full Body", ["zercher walk"]),
        row("Yoke Walk", "Full Body", ["yoke carry"]),
        row("Sandbag Carry", "Full Body", ["bear hug carry"]),
        row("Atlas Stone Lift", "Full Body", ["stone lift"]),
        row("Tire Flip", "Full Body", ["tractor tire flip"]),
        row("Sled Push", "Full Body", ["prowler push"]),
        row("Sled Pull", "Full Body", ["backward drag"]),
        row("Wall Ball", "Full Body", ["wallball shot"]),
        row("Medicine Ball Clean", "Full Body", ["mb clean"]),
        row("Medicine Ball Throw", "Full Body", ["chest pass throw"]),
        row("Medicine Ball Rotational Throw", "Full Body", ["scoop throw"]),
        row("Bear Crawl", "Full Body", ["quadruped crawl"], .bodyweight),
        row("Crab Walk", "Full Body", ["crab crawl"], .bodyweight),
        row("Duck Walk", "Full Body", ["squat walk"]),
        row("Turkish Get-Up", "Full Body", ["tgu"]),
        row("Renegade Row to Press", "Full Body", ["row press complex"]),
        row("Clean and Press", "Full Body", ["barbell clean press"]),
        row("Hang Clean and Press", "Full Body", ["hang clean press"]),
        row("Rope Pull", "Full Body", ["sled rope pull"]),
        row("Sandbag Over Shoulder", "Full Body", ["bag toss"]),
        row("Sandbag Squat", "Full Body", ["bear hug squat"]),
        row("Sandbag Lunge", "Full Body", ["sandbag walking lunge"]),
        row("Med Ball Burpee", "Full Body", ["ball burpee"], .bodyweight),
        row("Sprawl", "Full Body", ["mma sprawl"], .bodyweight),
        row("Sprawl to Jump", "Full Body", ["sprawl jump"], .bodyweight),
        row("Sprinter Start", "Full Body", ["explosive start"], .bodyweight),
        row("Broad Jump", "Full Body", ["standing long jump"], .bodyweight),
        row("Box Jump", "Full Body", ["plyometric box jump"], .bodyweight),
        row("Depth Jump", "Full Body", ["reactive plyo jump"]),
        row("Clapping Push-Up", "Full Body", ["plyo push up"], .bodyweight),
        row("Plyo Push-Up", "Full Body", ["explosive push up"], .bodyweight),
        row("Battle Rope Wave", "Full Body", ["alternating waves"]),
        row("Resistance Band Squat Press", "Full Body", ["band thruster"]),
        row("Ring Muscle-Up", "Full Body", ["ring mu"], .bodyweight),
        row("Bar Muscle-Up", "Full Body", ["bar mu"], .bodyweight),

        // Olympic / Power
        row("Clean", "Olympic / Power", ["full clean", "squat clean"]),
        row("Power Clean", "Olympic / Power", ["power clean from floor"]),
        row("Hang Clean", "Olympic / Power", ["hang clean"]),
        row("Hang Power Clean", "Olympic / Power", ["hang power clean"]),
        row("Clean Pull", "Olympic / Power", ["clean pull from floor"]),
        row("Clean High Pull", "Olympic / Power", ["clean high pull"]),
        row("Clean and Jerk", "Olympic / Power", ["c and j"]),
        row("Power Jerk", "Olympic / Power", ["power jerk"]),
        row("Split Jerk", "Olympic / Power", ["split jerk"]),
        row("Push Jerk", "Olympic / Power", ["push jerk"]),
        row("Snatch", "Olympic / Power", ["full snatch"]),
        row("Power Snatch", "Olympic / Power", ["power snatch from floor"]),
        row("Hang Snatch", "Olympic / Power", ["hang snatch"]),
        row("Hang Power Snatch", "Olympic / Power", ["hang power snatch"]),
        row("Snatch Pull", "Olympic / Power", ["snatch pull"]),
        row("Snatch High Pull", "Olympic / Power", ["snatch high pull"]),
        row("Muscle Snatch", "Olympic / Power", ["muscle snatch"]),
        row("Muscle Clean", "Olympic / Power", ["muscle clean"]),
        row("High Pull", "Olympic / Power", ["barbell high pull"]),
        row("Block Clean", "Olympic / Power", ["clean from blocks"]),
        row("Block Snatch", "Olympic / Power", ["snatch from blocks"]),
        row("Deficit Snatch", "Olympic / Power", ["snatch from deficit"]),
        row("Deficit Clean", "Olympic / Power", ["clean from deficit"]),
        row("Tall Clean", "Olympic / Power", ["tall clean drill"]),
        row("Tall Snatch", "Olympic / Power", ["tall snatch drill"]),
        row("Snatch Balance", "Olympic / Power", ["heaving snatch balance"]),
        row("Clean Grip Deadlift", "Olympic / Power", ["clean deadlift"]),
        row("Jerk Dip Squat", "Olympic / Power", ["jerk support squat"]),
        row("Jerk Recovery", "Olympic / Power", ["split recovery"]),
        row("Press in Snatch", "Olympic / Power", ["sots press"]),
        row("Snatch Push Press", "Olympic / Power", ["heaving snatch PP"]),
        row("Clean and Front Squat", "Olympic / Power", ["clean plus front squat"]),
        row("Snatch Pull Under", "Olympic / Power", ["pull under drill"]),
        row("Power Snatch from Blocks", "Olympic / Power", ["block power snatch"]),
        row("Power Clean from Blocks", "Olympic / Power", ["block power clean"]),
        row("Squat Jerk", "Olympic / Power", ["squat style jerk"]),
        row("Behind-the-Neck Jerk", "Olympic / Power", ["btnj"]),
        row("Snatch Deadlift", "Olympic / Power", ["first pull snatch"]),
        row("Clean Deadlift", "Olympic / Power", ["first pull clean"]),
        row("Segment Snatch", "Olympic / Power", ["paused snatch"]),
        row("Segment Clean", "Olympic / Power", ["paused clean"]),
        row("No-Feet Snatch", "Olympic / Power", ["no feet snatch drill"]),
        row("No-Feet Clean", "Olympic / Power", ["no feet clean drill"]),
        row("Hang Snatch Below Knee", "Olympic / Power", ["below knee snatch"]),
        row("Hang Clean Below Knee", "Olympic / Power", ["below knee clean"]),
        row("Snatch from Power Position", "Olympic / Power", ["hip snatch"]),
        row("Clean from Power Position", "Olympic / Power", ["hip clean"]),
        row("Jerk Drive", "Olympic / Power", ["jerk dip drive"]),
        row("Pin Squat", "Olympic / Power", ["anderson squat"]),
        row("Speed Deadlift", "Olympic / Power", ["dynamic effort deadlift"]),
        row("Speed Squat", "Olympic / Power", ["dynamic effort squat"]),
        row("Speed Bench", "Olympic / Power", ["dynamic effort bench"]),
        row("Band-Resisted Squat", "Olympic / Power", ["band squat"]),
        row("Chain Squat", "Olympic / Power", ["chain squat"]),
        row("Chain Bench Press", "Olympic / Power", ["chain bench"]),
        row("Reverse Band Bench", "Olympic / Power", ["reverse band bench"]),
        row("Slingshot Bench Press", "Olympic / Power", ["slingshot bench"]),
        row("Competition Bench Press", "Olympic / Power", ["powerlifting bench"]),

        // Mobility
        row("World's Greatest Stretch", "Mobility", ["wgs", "worlds greatest stretch", "stretch", "mobility", "warm up", "hips"], .mobility),
        row("Hip Flexor Stretch", "Mobility", ["kneeling hip flexor", "stretch", "mobility", "hips", "warm up"], .mobility),
        row("Couch Stretch", "Mobility", ["quad couch stretch"], .mobility),
        row("Hamstring Stretch", "Mobility", ["seated hamstring stretch"], .mobility),
        row("Standing Hamstring Stretch", "Mobility", ["toe touch stretch"], .mobility),
        row("Calf Stretch", "Mobility", ["wall calf stretch"], .mobility),
        row("Adductor Rockback", "Mobility", ["groin rockback"], .mobility),
        row("90-90 Hip Switch", "Mobility", ["shin box switch"], .mobility),
        row("Pigeon Stretch", "Mobility", ["figure four stretch"], .mobility),
        row("Thoracic Rotation", "Mobility", ["open book", "stretch", "mobility", "thoracic", "warm up"], .mobility),
        row("Cat-Cow", "Mobility", ["cat cow", "stretch", "mobility", "warm up"], .mobility),
        row("Shoulder Pass-Through", "Mobility", ["dowel pass through", "stretch", "mobility", "shoulders", "warm up"], .mobility),
        row("Banded Shoulder External Rotation", "Mobility", ["band external rotation"], .mobility),
        row("Banded Shoulder Internal Rotation", "Mobility", ["band internal rotation"], .mobility),
        row("Ankle Dorsiflexion Drill", "Mobility", ["knee over toe"], .mobility),
        row("Foam Roller Thoracic Extension", "Mobility", ["t spine roll"], .mobility),
        row("Foam Roll Quadriceps", "Mobility", ["quad foam roll"], .mobility),
        row("Foam Roll Hamstrings", "Mobility", ["hamstring roll"], .mobility),
        row("Foam Roll IT Band", "Mobility", ["it band roll"], .mobility),
        row("Foam Roll Calves", "Mobility", ["calf roll"], .mobility),
        row("Foam Roll Lats", "Mobility", ["lat roll"], .mobility),
        row("Lacrosse Ball Glute", "Mobility", ["glute smash"], .mobility),
        row("Lacrosse Ball Pec", "Mobility", ["pec smash"], .mobility),
        row("Wall Slide", "Mobility", ["scapular wall slide"], .mobility),
        row("Quadruped Extension-Rotation", "Mobility", ["quad er"], .mobility),
        row("Child's Pose", "Mobility", ["yoga childs pose"], .mobility),
        row("Downward Dog", "Mobility", ["adho mukha"], .mobility),
        row("Upward Dog", "Mobility", ["cobra stretch"], .mobility),
        row("Thread the Needle", "Mobility", ["t spine thread"], .mobility),
        row("Book Opener", "Mobility", ["lying t rotation"], .mobility),
        row("Frog Stretch", "Mobility", ["groin frog"], .mobility),
        row("Deep Squat Hold", "Mobility", ["asian squat hold"], .mobility),
        row("Overhead Squat Hold", "Mobility", ["oh squat mobility"], .mobility),
        row("Wrist Circles", "Mobility", ["wrist warmup"], .mobility),
        row("Ankle Circles", "Mobility", ["ankle circles"], .mobility),
        row("Hip Circles", "Mobility", ["hip CAR"], .mobility),
        row("Shoulder CAR", "Mobility", ["shoulder CARs"], .mobility),
        row("Neck CAR", "Mobility", ["neck controlled articular"], .mobility),
        row("Scapular CAR", "Mobility", ["scap CAR"], .mobility),
        row("Jefferson Curl", "Mobility", ["light jefferson curl"], .mobility),
        row("Standing Forward Fold", "Mobility", ["toe touch hold"], .mobility),
        row("Seated Forward Fold", "Mobility", ["pike stretch"], .mobility),
        row("Figure-Four Stretch", "Mobility", ["seated figure four"], .mobility),
        row("Supine Twist", "Mobility", ["lying spinal twist"], .mobility),
        row("Happy Baby", "Mobility", ["yoga happy baby"], .mobility),
        row("Puppy Pose", "Mobility", ["melting heart"], .mobility),
        row("Lat Stretch", "Mobility", ["doorway lat stretch"], .mobility),
        row("Doorway Pec Stretch", "Mobility", ["chest doorway stretch"], .mobility),
        row("Cross-Body Shoulder Stretch", "Mobility", ["sleeper stretch prep"], .mobility),
        row("Sleeper Stretch", "Mobility", ["posterior shoulder stretch"], .mobility),
        row("W-ind Stretch", "Mobility", ["prone shoulder w"], .mobility),
        row("Brettzel", "Mobility", ["side lying t spine"], .mobility),
        row("Quadruped Rockback", "Mobility", ["child pose rockback"], .mobility),
        row("Hip Airplane", "Mobility", ["single leg hip rotation"], .mobility),
        row("Shin Box Switch", "Mobility", ["90 90 switch"], .mobility),
        row("Lunge with Rotation", "Mobility", ["worlds greatest lunge"], .mobility),
        row("Walking Spiderman", "Mobility", ["spiderman lunge"], .mobility),
        row("Inchworm", "Mobility", ["walkout stretch"], .mobility),
        row("Leg Swing Front", "Mobility", ["dynamic leg swing"], .mobility),
        row("Leg Swing Lateral", "Mobility", ["lateral leg swing"], .mobility),
        row("Arm Circle", "Mobility", ["shoulder circles"], .mobility),
        row("Band Dislocate", "Mobility", ["band shoulder dislocate"], .mobility),
        row("PVC Overhead Squat", "Mobility", ["pvc oh squat"], .mobility),
        row("Wall Ankle Mobilization", "Mobility", ["wall ankle mob"], .mobility),
        row("Calf Raise Stretch", "Mobility", ["eccentric calf stretch"], .mobility),
        row("Tibialis Stretch", "Mobility", ["toe pull stretch"], .mobility),
        row("QL Stretch", "Mobility", ["side bend stretch"], .mobility),
        row("Prayer Stretch", "Mobility", ["child pose lat"], .mobility),
        row("Scorpion Stretch", "Mobility", ["prone scorpion"], .mobility),
        row("Cossack Mobility", "Mobility", ["cossack rock"], .mobility),
        row("Deep Lunge Hold", "Mobility", ["hip flexor hold"], .mobility),
        row("Supported Squat Hold", "Mobility", ["goblet squat hold"], .mobility),
        row("Diaphragmatic Breathing", "Mobility", ["breathing drill"], .mobility),
        row("Foam Roll Thoracic", "Mobility", ["upper back roll"], .mobility),
        row("Stick Rollout", "Mobility", ["stick mobility"], .mobility),
        row("Resistance Band Hip Distraction", "Mobility", ["banded hip distraction"], .mobility),
        row("Banded Ankle Mobilization", "Mobility", ["band ankle mob"], .mobility),
        row("Elevated Pigeon", "Mobility", ["box pigeon"], .mobility),
        row("Standing Quad Stretch", "Mobility", ["flamingo stretch"], .mobility),
        row("Lying Glute Stretch", "Mobility", ["supine glute stretch"], .mobility),
        row("Seated Glute Stretch", "Mobility", ["chair glute stretch"], .mobility),
        row("Overhead Triceps Stretch", "Mobility", ["triceps overhead stretch"], .mobility),
        row("Cross-Body Triceps Stretch", "Mobility", ["triceps pull across"], .mobility),
        row("Forearm Stretch", "Mobility", ["wrist flexor stretch"], .mobility),
        row("Forearm Extensor Stretch", "Mobility", ["wrist extensor stretch"], .mobility),
        row("Finger Extension Stretch", "Mobility", ["finger stretch"], .mobility),
        row("Neck Stretch", "Mobility", ["gentle neck stretch"], .mobility),
        row("Upper Trap Stretch", "Mobility", ["ear to shoulder stretch"], .mobility),
        row("Levator Scapulae Stretch", "Mobility", ["levator stretch"], .mobility),
        row("Dynamic Hip Flexor", "Mobility", ["walking hip flexor"], .mobility),
        row("Dynamic Hamstring", "Mobility", ["walking hamstring"], .mobility),
        row("Skip A", "Mobility", ["a skip warmup"], .mobility),
        row("Skip B", "Mobility", ["b skip warmup"], .mobility),
        row("Carioca", "Mobility", ["grapevine drill"], .mobility),
        row("High Knee March", "Mobility", ["marching warmup"], .mobility),
        row("Butt Kick March", "Mobility", ["heel to glute march"], .mobility)
    ]

    static func seedIfNeeded(context: ModelContext) throws {
        let existing = try context.fetch(FetchDescriptor<Exercise>())
        var existingByNormalizedName: [String: Exercise] = [:]
        for exercise in existing {
            existingByNormalizedName[normalizedKey(exercise.name)] = exercise
        }

        for item in items {
            let metadata = encodeMetadata(item.aliases)
            let key = normalizedKey(item.name)
            if let stored = existingByNormalizedName[key] {
                // Keep user-facing name/category untouched; refresh metadata, source, and catalog logging type.
                stored.searchMetadata = metadata
                stored.source = .builtIn
                stored.loggingType = item.loggingType
            } else {
                context.insert(
                    Exercise(
                        name: item.name,
                        category: item.category,
                        searchMetadata: metadata,
                        source: .builtIn,
                        loggingType: item.loggingType
                    )
                )
            }
        }
        try context.save()
    }

    private static func encodeMetadata(_ aliases: [String]) -> String {
        aliases
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
            .joined(separator: "\n")
    }

    private static func normalizedKey(_ raw: String) -> String {
        raw.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }
}

